version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=1
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
    restart: always